
export const Users = [
  {
    id: 1,
    nickname: "nazar",
    login: "nazarbek",
    password: "12345",
    profilname: "代翁曖)",
    img: "https://steamuserimages-a.akamaihd.net/ugc/957480811955081596/E7E9FC9147013120A6D23317A249F533CB92DDF4/?imw=512&amp;imh=529&amp;ima=fit&amp;impolicy=Letterbox&amp;imcolor=%23000000&amp;letterbox=true",
    profilpublication: "1",
    profilfollowers: "95",
    profilfollower: "138",
    threads: "ggwp_legendary",
    description: "We work on the soul to find peace",

  },
  {
    id: 2,
    nickname: "nurseit",
    login: "nurseit",
    password: "12345",
    profilname: "Мебель на заказ в городе ош",
    img: "https://avatars.mds.yandex.net/i?id=3324a1698bc83574c40089f1bc7fe9af_l-5387132-images-thumbs&n=13",
    profilpublication: "0",
    profilfollowers: "95",
    profilfollower: "138",
    threads: "nurseit",
    description: "Все виды мебели на заказ:",

  },
  {
    id: 3,
    nickname:"g.g.g.g",
    login:"g.g.g.g",
    password:"12345",
    profilname: "g.g.g.g",
    img: "https://vtp-club.ru/img/user.png",
    profilpublication:"0",
    profilfollowers: "95",
    profilfollower: "138",
    threads:"g.g.g.g",
    description:"",
    user1: 1,
    user2: 2,
    
  },
  {
    id: 4,
    nickname:"real_erlan",
    login:"real_erlan",
    password:"12345",
    profilname: "Cool-B",
    img: "https://sputnik.kg/img/07e7/03/03/1073285435_268:0:1334:1066_1920x0_80_0_0_d517444121ad2259ab1efab9f8096faa.png",
    profilpublication:"0",
    profilfollowers: "95",
    profilfollower: "138",
    threads:"real_erlan",
    description:"",
    user1: 1,
    user2: 2,
  },
  {
    id: 5,
    nickname:"anarbek.9908",
    login:"anarbek.9908",
    password:"12345",
    profilname: "Анарбек кожомберди уулу",
    img: "https://vtp-club.ru/img/user.png",
    profilpublication:"0",
    profilfollowers: "95",
    profilfollower: "138",
    threads:"anarbek.9908",
    description:"",
    user1: 1,
    user2: 2,
  },
  {
    id: 6,
    nickname:"imindjanov_n",
    login:"imindjanov_n",
    password:"12345",
    profilname: "Nursaid",
    img: "https://bugaga.ru/uploads/posts/2021-01/1610356568_vmeste-1.jpg",
    profilpublication:"0",
    profilfollowers: "95",
    profilfollower: "138",
    threads:"anarbek.9908",
    description:"With every hardship there is ease 94:6🔹️Мастер спорта по Боксу🔹️Нац. сборная команда КР🇰🇬🔹️Master of Sports in Boxing🔹️National Boxing Team🇰🇬",
    user1: 1,
    user2: 2,
  },
  {
    id: 7,
    nickname:"turatov0070",
    login:"turatov0070",
    password:"12345",
    profilname: "Аскат",
    img: "https://i.pinimg.com/originals/95/e5/43/95e54399ed583d9829aa28f88c7a7724.jpg",
    profilpublication:"0",
    profilfollowers: "95",
    profilfollower: "138",
    threads:"turatov0070",
    description:"",
    user1: 1,
    user2: 2,
  },
  {
    id: 8,
    nickname:"01.muli",
    login:"01.muli",
    password:"12345",
    profilname: "01.muli",
    img: "https://4tololo.ru/sites/default/files/images/20162001154422.jpg",
    profilpublication:"0",
    profilfollowers: "95",
    profilfollower: "138",
    threads:"01.muli",
    description:"",
    user1: 1,
    user2: 2,
  },
  {
    id: 9,
    nickname:"mtulanbaev05",
    login:"mtulanbaev05",
    password:"12345",
    profilname: "М Туланбаев",
    img: "https://vtp-club.ru/img/user.png",
    profilpublication:"0",
    profilfollowers: "95",
    profilfollower: "138",
    threads:"mtulanbaev05",
    description:"",
    user1: 1,
    user2: 2,
  },
  {
    id: 10,
    nickname:"msl.aval",
    login:"msl.aval",
    password:"12345",
    profilname: "Авал",
    img: "https://bugaga.ru/uploads/posts/2020-03/1585556842_morf-13.jpg",
    profilpublication:"0",
    profilfollowers: "95",
    profilfollower: "138",
    threads:"msl.aval",
    description:"",
    user1: 1,
    user2: 2,
  },
  {
    id: 11,
    nickname:"rus_anarbaev",
    login:"rus_anarbaev",
    password:"12345",
    profilname: "Рус Рус",
    img: "https://img.razrisyika.ru/kart/141/560626-chimin-7.jpg",
    profilpublication:"0",
    profilfollowers: "95",
    profilfollower: "138",
    threads:"rus_anarbaev",
    description:"",
    user1: 1,
    user2: 2,
  },

]


export const messages = [
  {
    id: 1,
    user_id: 2,
    message: "Я в Москве",
    chat_id: 2,
    profilname: "nurseit",
    img: "https://avatars.mds.yandex.net/i?id=3324a1698bc83574c40089f1bc7fe9af_l-5387132-images-thumbs&n=13",
    profil_id: 4,

  },
  {
    id: 2,
    user_id: 1,
    message: "Так рано проснулась",
    chat_id: 3,
    profilname: "g.g.g.g",
    img: "https://vtp-club.ru/img/user.png",
    profil_id: 4,
    
  },
  {
    id: 3,
    user_id: 2,
    message: "А что случилось",
    chat_id: 4,
    profilname: "real_erlan",
    img: "https://sputnik.kg/img/07e7/03/03/1073285435_268:0:1334:1066_1920x0_80_0_0_d517444121ad2259ab1efab9f8096faa.png",
    profil_id: 4,
  },

  {
    id: 4,
    user_id: 1,
    message: "Ааа",
    chat_id: 5,
    profilname: "Анарбек кожомберди уулу",
    img: "https://vtp-club.ru/img/user.png",
    profil_id: 4,
  },
  {
    id: 5,
    user_id: 2,
    message: "Привет",
    chat_id: 6,
    profilname: "Nursaid",
    img: "https://bugaga.ru/uploads/posts/2021-01/1610356568_vmeste-1.jpg",
    profil_id: 4,
  },
  {
    id: 6,
    user_id: 1,
    message: "как ты",
    chat_id: 7,
    profilname: "Аскат",
    img: "https://i.pinimg.com/originals/95/e5/43/95e54399ed583d9829aa28f88c7a7724.jpg",
    profil_id: 4,
  },
  {
    id: 7,
    user_id: 2,
    message: "я сейчас",
    chat_id: 8,
    profilname: "01.muli",
    img: "https://4tololo.ru/sites/default/files/images/20162001154422.jpg",
    profil_id: 4,
  },
  {
    id: 8,
    user_id: 1,
    message: "Кандайсын",
    chat_id: 9,
    profilname: "М Туланбаев",
    img: "https://vtp-club.ru/img/user.png",
    profil_id: 4,
  },
  {
    id: 9,
    user_id: 2,
    message: "Эмне болду",
    chat_id: 10,
    profilname: "Авал",
    img: "https://bugaga.ru/uploads/posts/2020-03/1585556842_morf-13.jpg",
    profil_id: 4,
  },
  {
    id: 10,
    user_id: 1,
    message: "Я отправил",
    chat_id: 11,
    profilname: "Рус Рус",
    img: "https://img.razrisyika.ru/kart/141/560626-chimin-7.jpg",
    profil_id: 4,
  },

]





export const posts = [
  {
    id: 1,
    user_id: 1,
    img: "https://cdn.smehost.net/2020sonymusiccouk-ukprod/wp-content/uploads/2015/12/a722e84b4d74f236f0096f80b3f2c5de-800x800.jpg",
    postaccount: "Nazar",
    posttext:"Кирре Горвелл-Даль, более известный под своим сценическим именем Kygo — норвежский диджей и музыкальный продюсер. Получил международное внимание со своим ремиксом на песню «I See Fire» исполнителя Эда Ширана, у которого более 50 миллионов прослушиваний на SoundCloud и 65 миллионов просмотров на YouTube",
    postheshteg: "#общество_newsKG",
    postcommnet: 110,
  },
  {
    id: 2,
    user_id: 2,
    img:"https://coliseum-mebel.ru/wp-content/uploads/2020/06/euromebel.jpg",
    postaccount: "Nurseit",
    posttext: "Какой самый лучший материал для мебели?  Предпочтительнее приобретать мебель из твердых пород древесины, которые обладают высокой прочностью и долговечностью. К таким породам относятся дуб, бук, ясень, орех и вишня.",
    postheshteg: "#Мебели европейские",
    postcommnet: 29,
  },
  {
    id: 3,
    user_id: 3,
    img:"https://ejin.ru/wp-content/uploads/2017/09/14-704.jpg",
    postaccount: "g.g.g.g",
    posttext: "Лес можно сравнить с большим многоэтажным домом. Растения растут в несколько ярусов. Самые высокие деревья образуют верхний ярус, немного ниже — низкорослые деревья, ещё ниже — ярус кустарников и ярус трав, самый нижний ярус занимают мхи и лишайники. Лес называют природным сообществом.    ",
    postheshteg: "Лесная природа",
    postcommnet: 29,
  },
  {
    id: 4,
    user_id: 4,
    img:"https://i.pinimg.com/originals/62/ef/55/62ef5523033037c8d7e464c6d4d0bbf0.jpg",
    postaccount: "real_erlan",
    posttext: "Что в природе розового цвета?    Водоросль называется Dunaliella Salina. Она окрашивает воду озера за счет вырабатываемого бета-каротина. Соляные кристаллы озера окрашиваются в нежно-розовый оттенок, а местами в красный. Помимо цвета, водоросль придает характерный запах фиалок местной соли.",
    postheshteg: "real_erlan",
    postcommnet: 29,
  },
  {
    id: 5,
    user_id: 5,
    img:"https://kartinkin.net/pics/uploads/posts/2022-07/1657929326_72-kartinkin-net-p-simmetriya-v-prirode-priroda-krasivo-foto-79.jpg",
    postaccount: "anarbek.9908",
    posttext: "О́зеро — компонент гидросферы, представляющий собой естественно возникший водоём, заполненный в пределах озёрной чаши (озёрного ложа) водой и не имеющий непосредственного соединения с морем (океаном). В озёра могут впадать реки, ручьи и подземные источники.",
    postheshteg: "",
    postcommnet: 29,
  },
  {
    id: 6,
    user_id: 6,
    img:"https://gas-kvas.com/grafic/uploads/posts/2023-10/1696520595_gas-kvas-com-p-kartinki-kvadratnie-13.jpg",
    postaccount: "imindjanov_n",
    posttext: "В таком месте хочется остаться надолго, а уходить всегда немного грустно. Самые красивые высокогорные водоемы — это Шавлинские, Каракабакские, Каракольские, Кучерлинские, Туюкские и Мультинские озера, Акчан, Куйгук, Манас, Дарашколь, Ак-Кем, Башталинское, Садринское, Узункель.",
    postheshteg: "",
    postcommnet: 29,
  },
  {
    id: 7,
    user_id: 7,
    img:"https://i.pinimg.com/originals/c9/35/36/c935361979796ec40df39e9c4a8203ed.jpg",
    postaccount: "turatov0070",
    posttext: "Онта́рио (англ. Lake Ontario, фр. Lac Ontario) — озеро на границе США и Канады, самое восточное и самое маленькое по площади в системе Великих озёр. С площадью 19 000 км² занимает 13-е место в списке крупнейших озёр мира, восьмой по площади пресноводный водоём Северной Америки.",
    postheshteg: "",
    postcommnet: 29,
  },
  {
    id: 8,
    user_id: 8,
    img:"https://gas-kvas.com/grafic/uploads/posts/2023-10/1696520592_gas-kvas-com-p-kartinki-kvadratnie-1.jpg",
    postaccount: "01.muli",
    posttext: "Вода охлаждается до +4 градусов Цельсия, становится более плотной и, соответственно, опускается на дно водоема. Теплые слои поднимаются вверх, где также охлаждаются и снова уходят на дно. Конвекция несколько замедляется после остужения всех слоев водоема до +4 градусов.",
    postheshteg: "",
    postcommnet: 29,
  },
  {
    id: 9,
    user_id: 9,
    img:"https://i.pinimg.com/originals/fe/5d/40/fe5d404dcea74436114e067f2c31d8dc.jpg",
    postaccount: "mtulanbaev05",
    posttext: "К собственно Великим озёрам относят пять крупнейших: Верхнее, Мичиган, Гурон, Эри и Онтарио. В систему также входит сравнительно небольшое озеро Сент-Клэр. Озеро Мичиган находится целиком в США, по остальным озёрам и соединяющим их коротким рекам проходит граница между США (⅔ акватории озёр) и Канадой (⅓ акватории).",
    postheshteg: "",
    postcommnet: 29,
  },
  {
    id: 10,
    user_id: 10,
    img:"https://celes.club/uploads/posts/2022-05/1651815385_45-celes-club-p-kvadrat-v-prirode-krasivo-foto-48.jpg",
    postaccount: "msl.aval",
    posttext: "Озеро — это замкнутое углубление суши, в которое стекают и накапливаются воды. Озёра не являются частью Мирового Океана. Море — это уже части Мирового океана, которые обособленны сушей или возвышениями подводного рельефа. Море имеет выход в Мировой океан, а озеро - нет",
    postheshteg: "",
    postcommnet: 29,
  },
  {
    id: 11,
    user_id: 11,
    img:"https://photocentra.ru/images/main58/583334_main.jpg",
    postaccount: "rus_anarbaev",
    posttext: "Радужные горы — чудо природы, ради которого люди готовы ехать буквально на край света. Например, в Перу, где для того, чтобы увидеть его, нужно забраться далеко в Анды на высоту около 5200 метров. Несмотря на труднодоступность, перуанские цветные горы стали популярной туристической локацией.",
    postheshteg: "",
    postcommnet: 29,
  },
]